In [2]:
import tensorflow as tf

In [13]:
hello = tf.constant("hello, tensorflow")
print(hello)

Tensor("Const_5:0", shape=(), dtype=string)


In [8]:
a = tf.constant(10)
b = tf.constant(5)
c = tf.add(a,b)
print(c)

Tensor("Add:0", shape=(), dtype=int32)


In [14]:
sess = tf.Session()

print(sess.run(hello))
print(sess.run([a,b,c]))

sess.close()

b'hello, tensorflow'
[10, 5, 15]


In [15]:
X = tf.placeholder(tf.float32,[None,3])
print(X)

Tensor("Placeholder:0", shape=(?, 3), dtype=float32)


In [16]:
x_data = [[1,2,3],[4,5,6]]

In [30]:
W = tf.Variable(tf.random_normal([3,2]))
b = tf.Variable(tf.random_normal([2,1]))

In [19]:
L = tf.Variable([[0.1,0.2],[0.3,0.4],[0.5,0.6]])

In [33]:
expt =tf.matmul(X,W)+ b

In [31]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [34]:
print("====== x_data========")
print(x_data)
print("====== W =====")
print(sess.run(W))
print("====== b =====")
print(sess.run(b))
print("====== L =====")
print(sess.run(L))
sess.close()

====== x_data========
[[1, 2, 3], [4, 5, 6]]
====== W =====
[[-0.09200969 -0.26065356]
 [ 1.1539092  -1.1394984 ]
 [ 0.11305733  0.03335192]]
====== b =====
[[1.8920934]
 [1.960026 ]]
====== L =====
[[0.1 0.2]
 [0.3 0.4]
 [0.5 0.6]]


In [97]:
x_data = [1,2,3]
y_data = [1,5,10]

In [107]:
X = tf.placeholder(tf.float32, name="X")
Y = tf.placeholder(tf.float32, name="Y")

In [108]:
hypo = W1*X*X +W2*X + b

In [109]:
cost = tf.reduce_mean(tf.square(hypo - Y))

In [110]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.1)
train_op = optimizer.minimize(cost)

In [111]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [105]:
    for step in range(100):
        _, cost_val = sess.run([train_op, cost], feed_dict={X: x_data, Y: y_data})
        print(step,cost_val,sess.run(W1),sess.run(W2),sess.run(b))

0 nan [nan] [nan] [nan]
1 nan [nan] [nan] [nan]
2 nan [nan] [nan] [nan]
3 nan [nan] [nan] [nan]
4 nan [nan] [nan] [nan]
5 nan [nan] [nan] [nan]
6 nan [nan] [nan] [nan]
7 nan [nan] [nan] [nan]
8 nan [nan] [nan] [nan]
9 nan [nan] [nan] [nan]
10 nan [nan] [nan] [nan]
11 nan [nan] [nan] [nan]
12 nan [nan] [nan] [nan]
13 nan [nan] [nan] [nan]
14 nan [nan] [nan] [nan]
15 nan [nan] [nan] [nan]
16 nan [nan] [nan] [nan]
17 nan [nan] [nan] [nan]
18 nan [nan] [nan] [nan]
19 nan [nan] [nan] [nan]
20 nan [nan] [nan] [nan]
21 nan [nan] [nan] [nan]
22 nan [nan] [nan] [nan]
23 nan [nan] [nan] [nan]
24 nan [nan] [nan] [nan]
25 nan [nan] [nan] [nan]
26 nan [nan] [nan] [nan]
27 nan [nan] [nan] [nan]
28 nan [nan] [nan] [nan]
29 nan [nan] [nan] [nan]
30 nan [nan] [nan] [nan]
31 nan [nan] [nan] [nan]
32 nan [nan] [nan] [nan]
33 nan [nan] [nan] [nan]
34 nan [nan] [nan] [nan]
35 nan [nan] [nan] [nan]
36 nan [nan] [nan] [nan]
37 nan [nan] [nan] [nan]
38 nan [nan] [nan] [nan]
39 nan [nan] [nan] [nan]
40 nan [na

In [95]:
print("X: 5, Y",sess.run(hypo, feed_dict={X: 5}))
print("X: 2.5, Y",sess.run(hypo, feed_dict={X: -1}))      

X: 5, Y [nan]
X: 2.5, Y [nan]


TypeError: random_normal() missing 1 required positional argument: 'shape'